import Head from "next/head";
// import CounterExample from "../components/CounterExample";
import HelloWorld from "../components/HelloWorld";
import Header from "../components/Header";
import Footer from "../components/Footer";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Udemy Course</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen">
        <div>
          <Header />
          <HelloWorld name="Arthur" />
          {/* <CounterExample /> */}
        </div>
      </main>

      <Footer />
    </div>
  );
}
